### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by karan** [fred-wang/MathMLinHTML5#1]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by fred-wang** [comment]
This repository has been moved to https://github.com/MathML/MathMLinHTML5 and I've opened https://github.com/MathML/MathMLinHTML5/issues/1. The gh-pages branch and repo will be deleted once @rgaiacs publishes the draft on the MathML website.
